---
- name: Add Apache security.conf into /etc/httpd/conf.d/
  copy:
    src: ../files/security.conf
    dest: /etc/httpd/conf.d/
  notify: restart apache

- name: Delete default contents & autoindex.
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/httpd/conf.d/autoindex.conf
    - /etc/httpd/conf.d/welcome.conf
    - /usr/share/httpd/icons/
  notify: restart apache

- name: Non-display indexes.
  replace:
    dest: /etc/httpd/conf/httpd.conf
    regexp: '^(.*)Options Indexes FollowSymLinks(.*)'
    replace: 'Options -Indexes +FollowSymLinks'
  notify: restart apache
